name: app_mobile
description: "Flutter App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.7
  toast: ^0.3.0
  lottie: ^3.1.2
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.2
  json_annotation: ^4.9.0
  dio: ^5.7.0
  internet_connection_checker_plus: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.4
  flutter_cache_manager: ^3.3.1
  intl: ^0.20.2
  rename: ^3.0.2
  args: ^2.5.0
  get: ^4.6.6
  get_it: ^8.0.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  cloud_firestore: ^6.0.3
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  provider: ^6.1.5+1
  http: ^1.2.2
  image_picker: ^1.2.0
  record: ^6.1.1
  just_audio: ^0.10.5
  video_player: ^2.10.0
  path: ^1.9.1
  mime: ^2.0.0
  just_waveform: ^0.0.7
  flutter_contacts: ^1.1.9+2
  phone_numbers_parser: ^9.0.11
  pinput: ^5.0.2
  zego_uikit_signaling_plugin: ^2.8.18
  shared_preferences_android: ^2.4.14
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  videosdk: ^3.0.0
  firebase_database: ^12.0.2
  cloudinary_public: ^0.23.1
  emoji_picker_flutter: ^4.3.0
  flutter_callkit_incoming: ^3.0.0
  flutter_ringtone_player: ^4.0.0+4
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/json/mockup/
    - assets/translations/
    - .env
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center