name: app_mobile
description: "Flutter App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.7
  toast: ^0.3.0
  lottie: ^2.6.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.2
  json_annotation: ^4.9.0
  dio: ^5.7.0
  internet_connection_checker_plus: ^1.0.0+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.4
  flutter_cache_manager: ^3.3.1
#  intl: ^0.19.0
  intl: ^0.20.2
  rename: ^3.0.2
  args: ^2.5.0
  get: ^4.6.6
  get_it: ^8.0.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/json/mockup/
    - assets/translations/
    - .env
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center